config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :heart_rhythms, only: [:index]
  root "application#home"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/heart_rhythm.rb
# frozen_string_literal: true

class HeartRhythm
  include Mongoid::Document

  field :time, type: DateTime
  field :value, type: Float

  def self.between(lower_bound = nil, upper_bound = nil)
    where(
      :time.gte => lower_bound.presence || time_bounds.first,
      :time.lte => upper_bound.presence || time_bounds.last,
    )
  end

  def self.time_bounds
    @time_bounds ||= [first, last].pluck(:time)
  end

  def self.stratified_sample(resolution: nil)
    resolution = resolution.presence&.to_i || 3
    slice_size = all.count.div(10**resolution)

    all.each_slice([slice_size, 1].max).map(&:last)
  end

  def as_chartable
    [time.to_i * 1000, value.to_f]
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def home
    @min_time, @max_time = HeartRhythm.time_bounds.map { _1.to_s(:picker) }
    @from = params[:from].presence || @min_time
    @to = params[:to].presence || @max_time
    @resolution = params[:resolution].presence || 3
  end
end

app/controllers/heart_rhythms_controller.rb
# frozen_string_literal: true

class HeartRhythmsController < ApplicationController
  def index
    sampled_subset =
      HeartRhythm
        .between(params[:from], params[:to])
        .stratified_sample(resolution: params[:resolution])
        .map(&:as_chartable)

    respond_to do |format|
      format.json { render json: sampled_subset, layout: false }
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/home.html.erb
<%= form_tag heart_rhythms_path(format: :json), method: :get,
    class: "w-1/8 inline-block mt-2",
    data: {
      chart_target: "form",
      action: "chart#update change->chart#update",
    } do %>
  <div class="isolate -space-y-px rounded-md shadow-sm my-2">
    <div class="relative rounded-md rounded-b-none px-3 pt-2.5 pb-1.5 ring-1 ring-inset ring-gray-300 focus-within:z-10 focus-within:ring-2 focus-within:ring-indigo-600">
      <label for="from" class="block text-xs font-medium text-gray-900">from</label>
      <%= datetime_field_tag :from, @from, min: @min_time, max: @max_time,
          class: "block border-0 p-0 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" %>
    </div>

    <div class="relative rounded-md rounded-t-none px-3 pt-2.5 pb-1.5 ring-1 ring-inset ring-gray-300 focus-within:z-10 focus-within:ring-2 focus-within:ring-indigo-600">
      <label for="to" class="block text-xs font-medium text-gray-900">to</label>
      <%= datetime_field_tag :to, @to, min: @min_time, max: @max_time,
          class: "block border-0 p-0 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" %>
    </div>
  </div>

  <div class="mt-2 flex rounded-md shadow-sm">
    <span class="inline-flex items-center rounded-l-md border border-r-0 border-gray-300 px-3 text-gray-900 sm:text-sm">
      resolution
    </span>
    <%= number_field_tag :resolution, @resolution, min: 2, max: 5,
        class: "block w-full min-w-0 flex-1 rounded-none rounded-r-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
  </div>
<% end %>

<figure class="highcharts-figure w-3/4 inline-block" data-chart-target="chart">
  <div id="container"></div>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HeartVibes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body data-controller="chart">
    <main class="container mx-auto mt-28 px-5 flex flex-row space-x-4">
      <%= yield %>
    </main>

    <div class="absolute right-1/2 bottom-1/2 transform translate-x-1/2 translate-y-1/2 hidden"
         data-chart-target="loading">
      <div class="border-t-transparent border-solid animate-spin  rounded-full border-blue-400 border-8 h-64 w-64"></div>
    </div>
  </body>
</html>